import Experience from "./Experience";
import "./Experiences.css";

import OpenInNewIcon from "@mui/icons-material/OpenInNew";
import KeyboardArrowRightIcon from "@mui/icons-material/KeyboardArrowRight";

export default function Experiences() {
  return (
    <div id="experiences">
      <label className="experience-label">Experience</label>
      <div className="experiences">
        <Experience
          duration={{ start: "Feb. 2025", end: "Aug. 2025" }}
          title="Software Engineer Intern"
          description={[
            "AWS Integrations Team",
            "Crawl AWS resources, generated by AWS service usage.",
            "Prototyped and deployed to production an early version of a caching solution to reduce the number of data collection jobs by 95%",
            "The project enabled Datadog customers to save an estimated $12M/year in AWS CloudWatch and auditing costs, while also reducing Datadog’s infrastructure expenses by $260k/year",
          ]}
          company="Datadog"
          techs={["Go", "AWS"]}
        />
        <Experience
          duration={{ start: "Sept. 2024", end: "Jan. 2025" }}
          title="Teaching Assistant (ACU)"
          description={[
            "Teaching computer science and programming to 3rd year students (Approx. 600 students).",
            "In charge of maintaining the 42sh (C) project (re-implementing Bash POSIX in C), with 3 other students.",
            'Assisted students in the "Intro to Compiler Design" project (building a compiler in C++).',
          ]}
          company="Epita"
          techs={["C", "Shell"]}
        />
        <Experience
          duration={{ start: "Jan. 2024", end: "July 2024" }}
          title="Teaching Assistant (YAKA)"
          description={[
            "Teaching Computer Science and Programming to 3rd year students",
          ]}
          company="Epita"
          techs={["Java", "C++", "Javascript"]}
        />
        <Experience
          duration={{ start: "Sept. 2023", end: "Jan. 2024" }}
          title="Backend Developer Intern"
          description={[
            "Added features and optimizations on the monolithic server",
            "Worked on the migration to micro services (written in Scala)",
          ]}
          company="Rakuten France"
          techs={["Java", "Scala", "ElasticSearch"]}
        />
        <Experience
          duration={{ start: "Sept. 2022", end: "July 2023" }}
          title="Teaching Assistant (ACDC)"
          description={[
            "Teaching Computer Science and Programming to first year students.",
            "Writing, testing and deploying weekly programming practicals for students in C#",
          ]}
          company="Epita Paris"
          techs={["C#"]}
        />
      </div>
      <div>
        {/*
	      <div className='resume-link'>
		<a href={process.env.PUBLIC_URL + '/sanassi_cv_ing1_en.pdf'}>
		  Open Full Résumé
		  <OpenInNewIcon />
		</a>
	      </div>
	      */}
      </div>
    </div>
  );
}
